In [16]:
import pandas as pd

df = pd.read_csv("sample.csv")

In [11]:
df

,symbol,upstream_seq,price,quantity,canceled,dott,market_center,sub_market_center,msn,omsn,sales_conditions,trade_date,date
0,MSFT,1524832,455.78,1.0,NaN,T,P,NaN,1524832,0,@FTI,1720774802192,2024-07-12
1,MSFT,1485376,455.52,2.0,NaN,T,K,NaN,1485376,0,@ TI,1720774656578,2024-07-12
2,MSFT,1524775,455.59,100.0,NaN,T,P,NaN,1524775,0,@FT,1720774802190,2024-07-12
3,MSFT,1384293,455.45,10.0,NaN,T,K,NaN,1384293,0,@FTI,1720774365549,2024-07-12
4,MSFT,1470647,455.37,10.0,NaN,T,P,NaN,1470647,0,@ TI,1720774603552,2024-07-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,AMZN,1286526,195.25,125.0,NaN,T,K,NaN,1286526,0,@FT,1720774040998,2024-07-12
129,AMZN,1365767,195.25,10.0,NaN,T,P,NaN,1365767,0,@ TI,1720774301835,2024-07-12
130,AMZN,1316967,195.25,498.0,NaN,T,P,NaN,1316967,0,@ T,1720774148244,2024-07-12
131,AMZN,1298127,195.28,1.0,NaN,T,K,NaN,1298127,0,@ TI,1720774078993,2024-07-12
132,AMZN,1384459,195.26,5.0,NaN,T,K,NaN,1384459,0,@FTI,1720774365609,2024-07-12

In [17]:
df["date"] = pd.to_datetime(df["trade_date"], unit="ms")
df["ticker"] = df["symbol"]

In [18]:
df.drop("trade_date", axis=1, inplace=True)
df.drop("symbol", axis=1, inplace=True)

In [20]:
df.to_csv("sample.csv", index=False)

In [21]:
import pandera as pa

/home/vscode/.local/lib/python3.10/site-packages/pandera/engines/pandas_engine.py:67: UserWarning: Using typeguard < 3. Generic types like List[TYPE], Dict[TYPE, TYPE] will only validate the first element in the collection.
  warnings.warn(

In [24]:
schema = pa.DataFrameSchema(
    {
        "quantity": pa.Column(
            float,
            checks=pa.Check.greater_than_or_equal_to(0),
        ),
    }
)

In [25]:
schema.validate(df)

SchemaError: column 'quanti' not in dataframe. Columns in dataframe: ['upstream_seq', 'price', 'quantity', 'canceled', 'dott', 'market_center', 'sub_market_center', 'msn', 'omsn', 'sales_conditions', 'date', 'ticker']